# support older version docker-compose
version: '3.3'
services:
  transmission:
    image: linuxserver/transmission:4.0.0
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/src
      - USER=transmission
      - PASS=transmission
    volumes:
      - ./web/src:/src
      - ./config:/config
      - ./downloads:/downloads
      - ./watch:/watch
    # work on windows or linux
    network_mode: "host"
    # work on mac
    # ports:
      # - 9091:9091
      # - 51413:51413
      # - 51413:51413/udp

    restart: unless-stopped
