name: Build

on:
  push:
    branches:
      - github-fix
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '23.11.0'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        env:
          VITE_APP_VERSION: ${{ github.ref_name }}
        run: pnpm build

      - name: Zip release folder
        run: cd dist && zip -r ../release.zip .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip