name: Build

on:
  push:
    branches:
      - github-fix
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install && npm install @tailwindcss/oxide-linux-x64-gnu

      - name: Build Project
        env:
          VITE_APP_VERSION: ${{ github.ref_name }}
        run: npm run build

      - name: Zip release folder
        run: cd dist && zip -r ../release.zip .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip